import { z } from 'zod'

import { EVIDENCE_LEVELS, GRAPH_SOURCES, PARADIGM_KEYS } from '@/lib/graph/types'

/**
 * Zod contracts for the NeuroPilot design API.
 *
 * `designRequestSchema` validates the body of POST /api/design.
 * `prototypePlanSchema` validates every plan before it reaches the
 * frontend — whether generated by the LLM agent or by the deterministic
 * fallback — so both producers share one output contract.
 */

// ---------------------------------------------------------------------------
// Request
// ---------------------------------------------------------------------------

/** Modality options offered by the design form. */
export const MODALITY_INPUTS = ['EEG', 'fNIRS', 'unknown'] as const

export type ModalityInput = (typeof MODALITY_INPUTS)[number]

export const designRequestSchema = z.object({
  /** The user's free-text BCI objective. */
  goal: z
    .string()
    .trim()
    .min(12, 'Describe your BCI idea in at least 12 characters.')
    .max(2000, 'Please keep your BCI idea under 2000 characters.'),
  /** Preferred recording modality; "unknown" means "I don't know yet". */
  modality: z.enum(MODALITY_INPUTS).default('unknown'),
  /** Hardware the user already owns, if any. */
  hardware: z.string().trim().max(300).optional(),
  /** Free-text constraints such as channel count or experience level. */
  constraints: z.string().trim().max(300).optional(),
})

export type DesignRequest = z.infer<typeof designRequestSchema>

// ---------------------------------------------------------------------------
// Plan building blocks
// ---------------------------------------------------------------------------

/** A named recommendation together with the reasoning behind it. */
export const namedReasonSchema = z.object({
  name: z.string().min(1),
  reason: z.string().min(1),
})

export type NamedReason = z.infer<typeof namedReasonSchema>

/** One ordered step of the experimental protocol or processing pipeline. */
export const planStepSchema = z.object({
  title: z.string().min(1),
  detail: z.string().min(1),
})

export type PlanStep = z.infer<typeof planStepSchema>

/** An artifact or confound the experimenter must watch for. */
export const planConfoundSchema = z.object({
  name: z.string().min(1),
  detail: z.string().min(1),
  /** Concrete way to reduce or monitor this confound, when one exists. */
  mitigation: z.string().optional(),
})

export type PlanConfound = z.infer<typeof planConfoundSchema>

/** One labeled hop in the graph-derived reasoning path. */
export const reasoningStepSchema = z.object({
  from: z.string().min(1),
  relationship: z.string().min(1),
  to: z.string().min(1),
  evidence: z.enum(EVIDENCE_LEVELS).optional(),
  note: z.string().optional(),
})

export type ReasoningPathStep = z.infer<typeof reasoningStepSchema>

/** A catalog dataset recommended only when genuinely relevant. */
export const relevantDatasetSchema = z.object({
  name: z.string().min(1),
  url: z.string().url(),
  why: z.string().min(1),
  /** Synthetic datasets must always be labeled as synthetic. */
  synthetic: z.boolean(),
})

export type RelevantDataset = z.infer<typeof relevantDatasetSchema>

// ---------------------------------------------------------------------------
// Plan
// ---------------------------------------------------------------------------

export const prototypePlanSchema = z.object({
  title: z.string().min(1),
  summary: z.string().min(1),

  /** The BCI paradigm the agent matched the goal to. */
  paradigm: namedReasonSchema,

  /** Human-readable modality recommendation, e.g. "EEG". */
  modality: z.string().min(1),

  neuralTarget: z.object({
    signals: z.array(z.string().min(1)).min(1),
    brainRegions: z.array(z.string().min(1)).min(1),
    reason: z.string().min(1),
  }),

  electrodes: z.object({
    recommended: z.array(z.string().min(1)).min(1),
    reason: z.string().min(1),
  }),

  hardware: z.object({
    /** May be empty when the user already has suitable hardware. */
    requirements: z.array(z.string().min(1)),
    reason: z.string().min(1),
  }),

  sampling: z.object({
    recommendation: z.string().min(1),
    reason: z.string().min(1),
  }),

  /** Experimental protocol as ordered steps. */
  protocol: z.array(planStepSchema).min(1),

  /** Signal-processing pipeline as ordered steps. */
  pipeline: z.array(planStepSchema).min(1),

  /** Features to extract from the processed signal. */
  features: z.array(z.string().min(1)).min(1),

  classifier: namedReasonSchema,

  /** How to check the prototype does more than chance. */
  validation: z.array(z.string().min(1)).min(1),

  /** Artifacts and confounds to control for. */
  confounds: z.array(planConfoundSchema).min(1),

  assumptions: z.array(z.string().min(1)).min(1),
  limitations: z.array(z.string().min(1)).min(1),

  /** Graph hops shown in the "Why did NeuroPilot recommend this?" panel. */
  reasoningPath: z.array(reasoningStepSchema).min(1),

  /** Only populated when a catalog dataset is genuinely relevant. */
  relevantDatasets: z.array(relevantDatasetSchema),
})

export type PrototypePlan = z.infer<typeof prototypePlanSchema>

// ---------------------------------------------------------------------------
// Response envelope
// ---------------------------------------------------------------------------

/** What produced the plan. */
export const PLAN_GENERATORS = ['llm', 'fallback'] as const

export type PlanGenerator = (typeof PLAN_GENERATORS)[number]

export const designPlanMetaSchema = z.object({
  /** Paradigm the agent matched the goal to. */
  paradigmKey: z.enum(PARADIGM_KEYS),
  /** Backend that supplied the graph context. */
  graphSource: z.enum(GRAPH_SOURCES),
  /** What generated the plan text. */
  generator: z.enum(PLAN_GENERATORS),
  /** Model id when generator is "llm", otherwise null. */
  model: z.string().nullable(),
  /** ISO 8601 timestamp. */
  generatedAt: z.string(),
})

export type DesignPlanMeta = z.infer<typeof designPlanMetaSchema>

export const designResponseSchema = z.object({
  plan: prototypePlanSchema,
  meta: designPlanMetaSchema,
})

export type DesignResponse = z.infer<typeof designResponseSchema>

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

export const DESIGN_ERROR_CODES = [
  'INVALID_INPUT',
  'UNSUPPORTED_OBJECTIVE',
  'GENERATION_FAILED',
] as const

export type DesignErrorCode = (typeof DESIGN_ERROR_CODES)[number]

export const designErrorResponseSchema = z.object({
  error: z.object({
    code: z.enum(DESIGN_ERROR_CODES),
    message: z.string().min(1),
    /** Extra context, e.g. the supported paradigm names. */
    details: z.array(z.string()).optional(),
  }),
})

export type DesignErrorResponse = z.infer<typeof designErrorResponseSchema>
